### ISSUE TITLE
"Error: open failed" while running openocd

### ISSUE THREAD

**Issue by vladislavmarkov** [forGGe/theCore-blinky#6]
Hi,

I had to change the line
`source [find interface/stlink-v2.cfg]`
to
`source [find interface/stlink-v2-1.cfg]`
**otherwise I get**
```
$ sudo openocd -f ../core/scripts/stm32f4discovery.cfg
[sudo] password for username: 
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Error: open failed
in procedure 'init' 
in procedure 'ocd_bouncer'
```
I have openocd v0.10.0 built with --enable-stlink.

**Comment by forGGe** [comment]
Thanks for reporting 

Could you please post here system you are running?
How about 
```
openocd -f board/stm32f4discovery.cfg
```

Does that give you correct results?

If it is ok, I will consider moving to the configuration supplied with openocd rather than saved in theCore.

**Comment by vladislavmarkov** [comment]
I'm running on.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
lsusb says:
`Bus 003 Device 007: ID 0483:374b STMicroelectronics ST-LINK/V2.1 (Nucleo-F103RB)`
So it seems, that I have to use stlink v2.1.
In stlink-2.cfg product id is 0x3748:
`hla_vid_pid 0x0483 0x3748`
Maybe, that's the problem.

**Comment by vladislavmarkov** [comment]
Nothing is changed when I typed:
`openocd -f board/stm32f4discovery.cfg`

**Comment by forGGe** [comment]
I guess I understood why you have this error. You have connected the Nucleo board with STM32F103 MCU, while currently theCore supports only STM32F4. 

To connect to it via openOCD, you probably need to select different board:
```
openocd -f board/st_nucleo_f103rb.cfg
```

But still, I'm not fully sure that current blinky example code for STM32F4 will run there smoothly. 

So, you have particular demand for STM32F1 MCU and you want to have theCore there, we need to do some work on adding platform drivers in https://github.com/forGGe/theCore/tree/develop/platform/stm32 and https://github.com/forGGe/theCore/tree/develop/platform/stm32/family.

Please specify what kind of functionality (which drivers) you expect there, and whether you want to be involved in the development or not.

If you don't want to wait until STM32F1 support will be added, I totally understand you :) If you are particularly interested in embedded C++ then take a look at http://xpcc.io/ framework (https://github.com/roboterclubaachen/xpcc , STM32F103 is supported there ) or ARM mbed https://www.mbed.com/en/

**Comment by forGGe** [comment]
forGGe/theCore#323 created as a result

**Comment by vladislavmarkov** [comment]
No, It's definitely not a STM32F103. Maybe the problem is that I'm using STM32F407G-DISC1 which is technically still a stm32f4discovery AFAIK. I guess that was a root of all the confusion.
All I had to do to make blinky work on STM32F407G-DISC1 is to change version of stlink from 2 to 2.1 in stm32f4discovery.cfg. Or it turns out I could simply do

`openocd -f board/stm32f429disc1.cfg`

since this cfg also uses stlink-v2-1.cfg.

BTW, openocd stm32f4discovery.cfg seems to be the same as the one from theCore ../core/scripts/stm32f4discovery.cfg so I guess switching to openocd configs won't change anything. 

Thanks for the links.

**Comment by vladislavmarkov** [comment]
Still confused because of lsusb output, though...
`Bus 003 Device 006: ID 0483:374b STMicroelectronics ST-LINK/V2.1 (Nucleo-F103RB)`

**Comment by forGGe** [comment]
From data brief:
> On-board ST-LINK/V2 on STM32F4DISCOVERY (old reference) or ST-LINK/V2-A on STM32F407G-DISC1 (new order code) 

http://www.st.com/content/ccc/resource/technical/document/data_brief/09/71/8c/4e/e4/da/4b/fa/DM00037955.pdf/files/DM00037955.pdf/jcr:content/translations/en.DM00037955.pdf

Seems that you've got newer revision of stm32 discovery board. I will update run instructions accordingly. Thanks!

P.S. I glad you have something that supported by theCore ;)
